# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0.

EXPECTED = FAILED

HARNESS_ENTRY = unsigned_overflow_check_harness
HARNESS_FILE = $(HARNESS_ENTRY).c

PROOF_SOURCES += $(HARNESS_FILE)

PROJECT_SOURCES += $(HARNESS_FILE)

include ../Makefile.common
